### ISSUE TITLE
PostPage error

### ISSUE THREAD

**Issue by michael-yin** [cnk/react_wagtail#1]
@cnk 

Thanks for your message.

I took some time to check your code and find the reason why you fail.

In `frontend/src/stories/PostPage.stories.js`

```
export const Example = () => {
  const mock = new MockAdapter(axios);
  mockPost(mock);
  mockTag(mock);

  return (
    <MemoryRouter initialEntries={["/post/1"]}>
      <Route path="/post/:id" component={PostPage} />
    </MemoryRouter>
  );
};
```

Notes:

1. You should use code like this so route `match` object is available in `this.props`

In `frontend/src/components/PostPage.js`

Please use `<PostDetail {...this.props} />` to pass the route params from `PostPage` to `PostDetail` component

**Comment by cnk** [comment]
@michael-yin Thank you so much! That fixed it and I can now move on with the rest of the tutorial. Thanks for the help and thank you so much for the excellent tutorial. I am learning so much!
